 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tasks_logs", type: :request do
  # TasksLog. As you add validations to TasksLog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TasksLog.create! valid_attributes
      get tasks_logs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tasks_log = TasksLog.create! valid_attributes
      get tasks_log_url(tasks_log)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tasks_log_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tasks_log = TasksLog.create! valid_attributes
      get edit_tasks_log_url(tasks_log)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TasksLog" do
        expect {
          post tasks_logs_url, params: { tasks_log: valid_attributes }
        }.to change(TasksLog, :count).by(1)
      end

      it "redirects to the created tasks_log" do
        post tasks_logs_url, params: { tasks_log: valid_attributes }
        expect(response).to redirect_to(tasks_log_url(TasksLog.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TasksLog" do
        expect {
          post tasks_logs_url, params: { tasks_log: invalid_attributes }
        }.to change(TasksLog, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tasks_logs_url, params: { tasks_log: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tasks_log" do
        tasks_log = TasksLog.create! valid_attributes
        patch tasks_log_url(tasks_log), params: { tasks_log: new_attributes }
        tasks_log.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tasks_log" do
        tasks_log = TasksLog.create! valid_attributes
        patch tasks_log_url(tasks_log), params: { tasks_log: new_attributes }
        tasks_log.reload
        expect(response).to redirect_to(tasks_log_url(tasks_log))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tasks_log = TasksLog.create! valid_attributes
        patch tasks_log_url(tasks_log), params: { tasks_log: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tasks_log" do
      tasks_log = TasksLog.create! valid_attributes
      expect {
        delete tasks_log_url(tasks_log)
      }.to change(TasksLog, :count).by(-1)
    end

    it "redirects to the tasks_logs list" do
      tasks_log = TasksLog.create! valid_attributes
      delete tasks_log_url(tasks_log)
      expect(response).to redirect_to(tasks_logs_url)
    end
  end
end
